name: Setup
description: Setup

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Rust cache
      id: rust-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db
          packages/cron_jobs/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build
      shell: bash
      run: cargo build --release
      if: steps.rust-cache.outputs.cache-hit != 'true'
      working-directory: packages/cron_jobs
