[project]
name = "weather-forecast-comparison"
version = "0.0.0"
dependencies = [
    "bs4>=0.0.2",
    "ipykernel>=6.29.5",
    "numpy>=2.1.2",
    "pandas-stubs>=2.2.3.241009",
    "pandas>=2.2.3",
    "types-beautifulsoup4>=4.12.0.20241020",
]
