[package]
name = "cron_jobs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.93", features = ["backtrace", "std"] }
async-trait = "0.1.83"
aws-config = "1.5.10"
aws-sdk-s3 = "1.63.0"
axum = { version = "0.7.6", features = ["macros"] }
axum-macros = "0.4.2"
chrono = "0.4.39"
csv = "1.3.1"
dotenvy = "0.15.7"
reqwest = "0.12.9"
scraper = "0.21.0"
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
