on:
  schedule:
    - cron: "0 0 * * *" # Run at 9 AM in JST

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Set AWS credentials to .env file
        run: |
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env

      - name: Harvest the observation weather data
        run: ./packages/cron_jobs/target/release/harvest_observation_weather_data
